#include "keypad25.h"

#define KC_ KC_TRNS
//#define VS_R_DBG LCTL(S(KC_F5))
//#define VS_RES LCTL(KC_PAUSE)

#define _BASE 0
#define _MEDIA 1

enum custom_keycodes {
    COMMENT = SAFE_RANGE, // comment selection
	UCOMMENT,             // uncomment current selection
	VS_BACK,              // previous cursor location
	VS_FWD,               // next cursor location
	VS_TODEF,             // collapse current scope
	VS_SEC_TOG,           // toggle collapse of current section
	VS_EXP_ALL,           // toggle expansion
	VS_RDEBUG,            // restart debugging
	OS_CUT,               // cut
	OS_COPY,              // coopy
	OS_PASTE              // paste
	//COOL_TAB
};

//Tap Dance Declarations
enum {
  TD_COPY_CUT = 0,
  TD_F5_DBL
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch(keycode) {
            case COMMENT:
                SEND_STRING(SS_LCTRL("k")SS_LCTRL("c")); // Comments selection in VS
                return false;
		    case UCOMMENT:
                SEND_STRING(SS_LCTRL("k")SS_LCTRL("u")); // Uncomments selection in VS
                return false;
			case VS_BACK:
                SEND_STRING(SS_LCTRL("-")); // Previous location
                return false;
            case VS_FWD:
                SEND_STRING(SS_LCTRL("_")); // next location
                return false;
            case VS_TODEF:
                SEND_STRING(SS_LCTRL("m")SS_LCTRL("o"));
				return false;
			case VS_SEC_TOG:
				SEND_STRING(SS_LCTRL("m")SS_LCTRL("m"));
				return false;
			case VS_EXP_ALL:
				SEND_STRING(SS_LCTRL("m")SS_LCTRL("l"));
				return false;
			case OS_CUT:
				SEND_STRING(SS_LCTRL("x"));
				return false;
			case OS_COPY:
				SEND_STRING(SS_LCTRL("c"));
				return false;
			case OS_PASTE:
				SEND_STRING(SS_LCTRL("v"));
				return false;
        }
    }
    return true;
};

//Tap Dance Definitions
qk_tap_dance_action_t tap_dance_actions[] = {
  // Single click to copy, double to cut.
  [TD_COPY_CUT] = ACTION_TAP_DANCE_DOUBLE(OS_COPY, OS_CUT)
  // single to start debugging, step debug.  Double to restart debugging.
  ,[TD_F5_DBL] = ACTION_TAP_DANCE_DOUBLE(KC_F5, LCTL(S(KC_F5)))
};

// tables generated by https://www.tablesgenerator.com/text_tables
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
// Base layer
// +-----------+-------------+-------------+---------+----------+
// | (Re)start |   Restart   |    Toggle   |  Abort  |   Layer  |
// | debugging |  debugging  | breakpoints | compile |    up    |
// +-----------+-------------+-------------+---------+----------+
// |  Comment  |  Uncomment  |     Copy    |   Cut   |   Paste  |
// | selection |  selection  |             |         |          |
// +-----------+-------------+-------------+---------+----------+
// |  Previous |     Page    |             |   Page  |   Next   |
// |   cursor  |      up     |      Up     |   down  |  cursor  |
// |  location |             |             |         | location |
// +-----------+-------------+-------------+---------+----------+
// |    Home   |     Left    |     Down    |  Right  |    End   |
// +-----------+-------------+-------------+---------+----------+
// |   Toggle  |   Collapse  |             |  Print  |   Cool   |
// |  collapse |      to     |  Expand all |  screen |    tab   |
// |  section  | Definitions |             |         |          |
// +-----------+-------------+-------------+---------+----------+
  [_BASE] = LAYOUT(
  TD(TD_F5_DBL), LCTL(S(KC_F5)), KC_F9,      LCTL(KC_PAUSE), TO(_MEDIA), \
  COMMENT,       UCOMMENT,       OS_COPY,    OS_CUT,         OS_PASTE, \
  VS_BACK,       KC_PGUP,        KC_UP,      KC_PGDN,        VS_FWD, \
  KC_HOME,       KC_LEFT,        KC_DOWN,    KC_RIGHT,       KC_END, \
  VS_SEC_TOG,    VS_TODEF,       VS_EXP_ALL, KC_PSCR,        LGUI(KC_TAB) \
  ),
  
// Media layer ::TESTING::
//+---------------+---------+-----------+---------+----------+
//| tap dance     |         |           |         |          |
//| start/restart | _______ | _______   | _______ | _______  |
//| debugging     |         |           |         |          |
//+---------------+---------+-----------+---------+----------+
//| tap dance     |         | Tap dance |         | layer    |
//| comment       | _______ | Copy      | _______ | down     |
//| uncomment     |         | Cut       |         |          |
//+---------------+---------+-----------+---------+----------+
//| Volume        | Volume  | Volume up |   LED   | Increase |
//| Down          | mute    |           | TOGGLE  |Brightness|
//+---------------+---------+-----------+---------+----------+
//| Previous      | Play/   |   Next    |RGB Mode | Decrease |
//| track         | Pause   |   track   |  Cycle  |Brightness|
//+---------------+---------+-----------+---------+----------+
//|  Static LED   | Breathe |   Swirl   | Rainbow | RGB Test |
//+---------------+---------+-----------+---------+----------+  
  [_MEDIA] = LAYOUT(
  TD(TD_F5_DBL), _______, _______,          _______, _______, \
  TD(TD_COM),    _______, TD( TD_COPY_CUT), _______, TO(_BASE), \
  KC_VOLD,       KC_MUTE, KC_VOLU,          RGB_TOG, RGB_VAI, \
  KC_MPRV,       KC_MPLY, KC_MNXT,          _______, RGB_VAD, \
  RGB_M_P,       RGB_M_B, RGB_M_SW,         RGB_M_R, RGB_M_T \
  )
};